---
- hosts: all
  become: yes
  tasks:
    - name: Adding node.js gpg key
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    - name: Adding node.js repository
      apt_repository:
        repo: deb https://deb.nodesource.com/node_12.x {{ ansible_lsb.codename | lower }} main
    - name: Install build-essential, ruby, sqlite3 and node.js are installed
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: latest
      loop:
        - build-essential
        - ruby-full
        - sqlite3
        - libsqlite3-dev
        - nodejs
    - name: Install yarn
      npm:
        name: yarn
        global: yes
    - name: Install rails
      gem:
        name: rails
        user_install: no
